# Getting Financial Data - Pandas Datareader

### Introduction:

This time you will get data from a website.


### Step 1. Import the necessary libraries

In [269]:
import pandas as pd 
from datetime import date 
import os 
from dotenv import load_dotenv
import yfinance as yf  # pandas_datareader isn't working so i found alt lib

### Step 2. Create your time range (start and end variables). The start date should be 01/01/2015 and the end should today (whatever your today is).

In [270]:
rng = pd.date_range(
    start='2015-01-01', 
    end=date.today(),
    freq='D'
)

rng

DatetimeIndex(['2015-01-01', '2015-01-02', '2015-01-03', '2015-01-04',
               '2015-01-05', '2015-01-06', '2015-01-07', '2015-01-08',
               '2015-01-09', '2015-01-10',
               ...
               '2026-08-13', '2026-08-14', '2026-08-15', '2026-08-16',
               '2026-08-17', '2026-08-18', '2026-08-19', '2026-08-20',
               '2026-08-21', '2026-08-22'],
              dtype='datetime64[us]', length=4252, freq='D')

### Step 3. Get an API key for one of the APIs that are supported by Pandas Datareader, preferably for AlphaVantage.

If you do not have an API key for any of the supported APIs, it is easiest to get one for [AlphaVantage](https://www.alphavantage.co/support/#api-key). (Note that the API key is shown directly after the signup. You do *not* receive it via e-mail.)

(For a full list of the APIs that are supported by Pandas Datareader, [see here](https://pydata.github.io/pandas-datareader/readers/index.html). As the APIs are provided by third parties, this list may change.)

### Step 4. Use Pandas Datarader to read the daily time series for the Apple stock (ticker symbol AAPL) between 01/01/2015 and today, assign it to df_apple and print it.

In [271]:
def get_data(ticker: str) -> pd.DataFrame:
    return yf.download(
        ticker,
        start=date(2015, 1, 1),
        end=date.today()
    )

df_apple = get_data('AAPL')
df_apple.head()

[*********************100%***********************]  1 of 1 completed

Price           Close       High        Low       Open     Volume
Ticker           AAPL       AAPL       AAPL       AAPL       AAPL
Date
2015-01-02  24.171759  24.638258  23.734000  24.627203  212818400
2015-01-05  23.490795  24.021411  23.305080  23.941819  257142000
2015-01-06  23.493010  23.751684  23.132632  23.554914  263188400
2015-01-07  23.822441  23.921931  23.590296  23.700841  160423600
2015-01-08  24.737749  24.795233  24.032472  24.149651  237458000

In [272]:
# some additional work w/df 
# decide to make a func in order not to repeat code 

def cleaner(df: pd.DataFrame) -> pd.DataFrame:
    df = df.droplevel(level=1, axis=1)
    df.columns.name = None 
    return df

df_apple = cleaner(df_apple)
df_apple.head()

                Close       High        Low       Open     Volume
Date
2015-01-02  24.171759  24.638258  23.734000  24.627203  212818400
2015-01-05  23.490795  24.021411  23.305080  23.941819  257142000
2015-01-06  23.493010  23.751684  23.132632  23.554914  263188400
2015-01-07  23.822441  23.921931  23.590296  23.700841  160423600
2015-01-08  24.737749  24.795233  24.032472  24.149651  237458000

### Step 5. Add a new column "stock" to the dataframe and add the ticker symbol

In [273]:
df_apple['stock'] = 'AAPL'
df_apple.head()

                Close       High        Low       Open     Volume stock
Date
2015-01-02  24.171759  24.638258  23.734000  24.627203  212818400  AAPL
2015-01-05  23.490795  24.021411  23.305080  23.941819  257142000  AAPL
2015-01-06  23.493010  23.751684  23.132632  23.554914  263188400  AAPL
2015-01-07  23.822441  23.921931  23.590296  23.700841  160423600  AAPL
2015-01-08  24.737749  24.795233  24.032472  24.149651  237458000  AAPL

### Step 6. Repeat the two previous steps for a few other stocks, always creating a new dataframe: Tesla, IBM and Microsoft. (Ticker symbols TSLA, IBM and MSFT.)

In [274]:
df_tesla = cleaner(get_data('TSLA'))
df_tesla['stock'] = 'TSLA'

df_ibm = cleaner(get_data('IBM'))
df_ibm['stock'] = 'IBM'

df_microsoft = cleaner(get_data('MSFT'))
df_microsoft['stock'] = 'MSFT'

[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed

### Step 7. Combine the four separate dataFrames into one combined dataFrame df that holds the information for all four stocks

In [275]:
df = pd.concat([df_apple, df_tesla, df_ibm, df_microsoft])
df.head()

                Close       High        Low       Open     Volume stock
Date
2015-01-02  24.171759  24.638258  23.734000  24.627203  212818400  AAPL
2015-01-05  23.490795  24.021411  23.305080  23.941819  257142000  AAPL
2015-01-06  23.493010  23.751684  23.132632  23.554914  263188400  AAPL
2015-01-07  23.822441  23.921931  23.590296  23.700841  160423600  AAPL
2015-01-08  24.737749  24.795233  24.032472  24.149651  237458000  AAPL

### Step 8. Shift the stock column into the index (making it a multi-level index consisting of the ticker symbol and the date).

In [276]:
df = df.set_index('stock', append=True)
df.head()

                      Close       High        Low       Open     Volume
Date       stock
2015-01-02 AAPL   24.171759  24.638258  23.734000  24.627203  212818400
2015-01-05 AAPL   23.490795  24.021411  23.305080  23.941819  257142000
2015-01-06 AAPL   23.493010  23.751684  23.132632  23.554914  263188400
2015-01-07 AAPL   23.822441  23.921931  23.590296  23.700841  160423600
2015-01-08 AAPL   24.737749  24.795233  24.032472  24.149651  237458000

### Step 7. Create a dataFrame called vol, with the volume values.

In [277]:
vol = df[['Volume']]
vol.head()

                     Volume
Date       stock
2015-01-02 AAPL   212818400
2015-01-05 AAPL   257142000
2015-01-06 AAPL   263188400
2015-01-07 AAPL   160423600
2015-01-08 AAPL   237458000

### Step 8. Aggregate the data of volume to weekly.
Hint: Be careful to not sum data from the same week of 2015 and other years.

In [278]:
vol['date_col'] = vol.index.get_level_values(0)
vol['year'] = vol.date_col.dt.year 
vol['week_number'] = vol.date_col.dt.isocalendar().week 

vol_pivot = pd.pivot_table(
    data=vol, 
    index=['year', 'week_number'],
    columns='stock', 
    values='Volume'
)

vol_pivot.head()

stock                    AAPL        IBM        MSFT        TSLA
year week_number
2015 1            212818400.0  5779673.0  27913900.0  71466000.0
     2            226602000.0  5115776.8  31765060.0  68128800.0
     3            243381280.0  4865950.2  31417640.0  92397600.0
     4            198737000.0  8170515.5  34338150.0  60793875.0
     5            372674160.0  6888537.8  87557360.0  47160600.0

### Step 9. Find all the volume traded in the year of 2015

In [279]:
vol_2015 = vol.loc[vol['year'] == 2015]

vol_pivot_2015 = pd.pivot_table(
    data=vol_2015, 
    index='year',
    columns='stock', 
    values='Volume', 
    aggfunc='sum'
)

vol_pivot_2015.head()

stock         AAPL         IBM        MSFT         TSLA
year
2015   52264199600  1156439400  9059455900  16323267000